import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import QRCode from "qrcode";
import { Ban, CalendarDays, Check, Clock3, Download, Loader2, MapPin, Plus, QrCode, Save, X } from "lucide-react";
import { FormEvent, useState } from "react";

const slugify = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
type FormState = { id?: number; title: string; description: string; startsAt: string; endsAt: string; venueName: string; address: string; organizer: string; capacity: string; price: string; accessibility: string; };
const emptyForm: FormState = { title: "", description: "", startsAt: "", endsAt: "", venueName: "", address: "", organizer: "", capacity: "", price: "Gratuito", accessibility: "" };

export default function AdminEvents() {
  const utils = trpc.useUtils();
  const { data: events, isLoading } = trpc.admin.events.useQuery({ slug: "adamantina" });
  const createEvent = trpc.admin.createEvent.useMutation({ onSuccess: () => { utils.admin.events.invalidate(); setForm(emptyForm); setOpen(false); } });
  const updateEvent = trpc.admin.updateEvent.useMutation({ onSuccess: () => { utils.admin.events.invalidate(); setForm(emptyForm); setOpen(false); } });
  const createQr = trpc.admin.createQrCode.useMutation({ onSuccess: async ({ code, expiresAt }) => { const canvas = document.createElement("canvas"); await QRCode.toCanvas(canvas, `${window.location.origin}/presenca/${code}`, { width: 480, margin: 2, color: { dark: "#123f36", light: "#ffffff" } }); const link = document.createElement("a"); link.download = `qr-evento-${code.slice(0, 8)}.png`; link.href = canvas.toDataURL("image/png"); link.click(); setQrStatus(`QR Code gerado. Expira em ${new Date(expiresAt).toLocaleString("pt-BR")}.`); if (qrEventId) utils.admin.qrCodes.invalidate({ slug: "adamantina", eventId: qrEventId }); } });
  const revokeQr = trpc.admin.revokeQrCode.useMutation({ onSuccess: () => { if (qrEventId) utils.admin.qrCodes.invalidate({ slug: "adamantina", eventId: qrEventId }); setQrStatus("QR Code revogado."); } });
  const [form, setForm] = useState<FormState>(emptyForm);
  const [open, setOpen] = useState(false);
  const [qrStatus, setQrStatus] = useState("");
  const [qrEventId, setQrEventId] = useState<number | null>(null);
  const { data: qrCodes } = trpc.admin.qrCodes.useQuery({ slug: "adamantina", eventId: qrEventId ?? 0 }, { enabled: Boolean(qrEventId) });

  const submit = async (event: FormEvent) => { event.preventDefault(); const payload = { slug: slugify(form.title), title: form.title, description: form.description || undefined, startsAt: new Date(form.startsAt), endsAt: form.endsAt ? new Date(form.endsAt) : undefined, venueName: form.venueName || undefined, address: form.address || undefined, organizer: form.organizer || undefined, capacity: form.capacity ? Number(form.capacity) : undefined, price: form.price || undefined, accessibility: form.accessibility || undefined, status: "approved" as const }; if (form.id) await updateEvent.mutateAsync({ id: form.id, tenantSlug: "adamantina", ...payload }); else await createEvent.mutateAsync({ tenantSlug: "adamantina", ...payload }); };
  const edit = (item: NonNullable<typeof events>[number]) => { setForm({ id: item.id, title: item.title, description: item.description ?? "", startsAt: new Date(item.startsAt).toISOString().slice(0, 16), endsAt: item.endsAt ? new Date(item.endsAt).toISOString().slice(0, 16) : "", venueName: item.venueName ?? "", address: item.address ?? "", organizer: item.organizer ?? "", capacity: item.capacity ? String(item.capacity) : "", price: item.price ?? "", accessibility: item.accessibility ?? "" }); setOpen(true); };
  const generateQr = async (eventId: number) => { setQrEventId(eventId); setQrStatus("Gerando QR Code…"); await createQr.mutateAsync({ slug: "adamantina", eventId, label: "Entrada principal" }); };

  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Badge className="border-0 bg-[#fff0d6] text-[10px] font-bold uppercase tracking-[0.16em] text-[#9a681d]">Agenda municipal</Badge><h2 className="mt-3 font-display text-3xl font-bold tracking-[-0.05em] text-[#123f36]">Eventos</h2><p className="mt-2 text-sm text-[#71827c]">Publique a agenda e meça a participação em cada evento.</p></div><Button onClick={() => { setForm(emptyForm); setOpen(true); }} className="rounded-xl bg-[#0d5c4d] font-bold text-white hover:bg-[#08483c]"><Plus className="mr-2 h-4 w-4" /> Novo evento</Button></div>
    {open && <Card className="rounded-[22px] border-[#cfe0d2] bg-white shadow-[0_12px_30px_rgba(39,73,57,0.08)]"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="font-display text-xl text-[#123f36]">{form.id ? "Editar evento" : "Novo evento"}</CardTitle><button onClick={() => setOpen(false)} className="rounded-lg p-2 text-[#71827c] hover:bg-[#f1f6f1]"><X className="h-4 w-4" /></button></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><Field label="Título"><Input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="Ex.: Festival de Inverno" /></Field><Field label="Organizador"><Input value={form.organizer} onChange={(e) => setForm({ ...form, organizer: e.target.value })} /></Field><Field label="Descrição" wide><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="min-h-24 w-full rounded-xl border border-[#dfe8e1] bg-white p-3 text-sm outline-none ring-[#7fb4a0] focus:ring-2" /></Field><Field label="Início"><Input required type="datetime-local" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} /></Field><Field label="Fim"><Input type="datetime-local" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} /></Field><Field label="Local"><Input value={form.venueName} onChange={(e) => setForm({ ...form, venueName: e.target.value })} placeholder="Praça Élio Micheloni" /></Field><Field label="Endereço"><Input value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></Field><Field label="Capacidade estimada"><Input type="number" min="0" value={form.capacity} onChange={(e) => setForm({ ...form, capacity: e.target.value })} /></Field><Field label="Preço"><Input value={form.price} onChange={(e) => setForm({ ...form, price: e.target.value })} /></Field><Field label="Acessibilidade" wide><Input value={form.accessibility} onChange={(e) => setForm({ ...form, accessibility: e.target.value })} placeholder="Recursos disponíveis no evento" /></Field><div className="md:col-span-2 flex justify-end border-t border-[#edf1ed] pt-4"><Button type="submit" disabled={createEvent.isPending || updateEvent.isPending} className="rounded-xl bg-[#0d5c4d] font-bold text-white">{createEvent.isPending || updateEvent.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />} Salvar evento</Button></div></form></CardContent></Card>}
    {qrStatus && <div className="flex items-center gap-2 rounded-xl border border-[#cfe0d2] bg-[#e8f1ea] px-4 py-3 text-sm font-semibold text-[#0d5c4d]"><Check className="h-4 w-4" /> {qrStatus}</div>}
    {qrEventId && qrCodes?.length ? <Card className="rounded-[22px] border-[#e0e8e0] bg-white"><CardHeader><CardTitle className="font-display text-xl text-[#123f36]">QR Codes deste evento</CardTitle></CardHeader><CardContent><div className="space-y-3">{qrCodes.map((qr) => <div key={qr.id} className="flex flex-col gap-3 rounded-xl bg-[#f5f8f5] p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold text-[#20332f]">{qr.label ?? "Código de acesso"}</p><p className="mt-1 text-xs text-[#71827c]">{qr.active && (!qr.expiresAt || new Date(qr.expiresAt) > new Date()) ? "Ativo" : "Inativo ou expirado"} · expira {qr.expiresAt ? new Date(qr.expiresAt).toLocaleString("pt-BR") : "sem data"}</p></div>{qr.active ? <Button variant="outline" onClick={() => revokeQr.mutate({ slug: "adamantina", id: qr.id })} disabled={revokeQr.isPending} className="rounded-lg border-[#ecc9c0] text-[#b4533d]"><Ban className="mr-2 h-4 w-4" /> Revogar</Button> : <Badge className="w-fit border-0 bg-[#edf1ed] text-[10px] uppercase text-[#71827c]">Revogado</Badge>}</div>)}</div></CardContent></Card> : null}
    <Card className="rounded-[22px] border-[#e0e8e0] bg-white shadow-[0_10px_25px_rgba(39,73,57,0.04)]"><CardHeader><CardTitle className="font-display text-xl text-[#123f36]">Agenda cadastrada <span className="ml-2 text-sm font-normal text-[#92a099]">{events?.length ?? 0}</span></CardTitle></CardHeader><CardContent>{isLoading ? <div className="flex items-center gap-2 py-8 text-sm text-[#71827c]"><Loader2 className="h-4 w-4 animate-spin" /> Carregando eventos…</div> : events?.length ? <div className="divide-y divide-[#edf1ed]">{events.map((item) => <div key={item.id} className="flex flex-col gap-3 py-4 lg:flex-row lg:items-center"><div className="flex h-12 w-12 shrink-0 flex-col items-center justify-center rounded-xl bg-[#fff0d6] text-[#9a681d]"><CalendarDays className="h-4 w-4" /><span className="mt-1 text-[10px] font-bold">{new Date(item.startsAt).toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" })}</span></div><div className="min-w-0 flex-1"><p className="font-bold text-[#20332f]">{item.title}</p><p className="mt-1 flex flex-wrap items-center gap-2 text-xs text-[#8a9a92]"><Clock3 className="h-3.5 w-3.5" /> {new Date(item.startsAt).toLocaleString("pt-BR")} <MapPin className="ml-2 h-3.5 w-3.5" /> {item.venueName ?? "Local pendente"}</p></div><Badge className="w-fit border-0 bg-[#e2f0e3] text-[10px] font-bold uppercase text-[#0d5c4d]">{item.status === "approved" ? "Publicado" : item.status}</Badge><div className="flex gap-2"><Button variant="outline" onClick={() => generateQr(item.id)} disabled={createQr.isPending} className="rounded-lg border-[#c9d9cc] text-[#0d5c4d]"><QrCode className="mr-2 h-4 w-4" /> QR Code</Button><Button variant="ghost" onClick={() => edit(item)} className="rounded-lg text-[#0d5c4d]"><PencilIcon /> Editar</Button></div></div>)}</div> : <div className="rounded-2xl bg-[#f5f8f5] p-8 text-center text-sm text-[#71827c]"><CalendarDays className="mx-auto mb-3 h-6 w-6 text-[#9bb3a1]" />Nenhum evento cadastrado ainda.</div>}</CardContent></Card>
  </div>;
}
function Field({ label, children, wide }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? "md:col-span-2 space-y-1.5" : "space-y-1.5"}><span className="text-xs font-bold uppercase tracking-wide text-[#71827c]">{label}</span>{children}</label>; }
function PencilIcon() { return <span className="mr-2">✎</span>; }
