import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { MapView } from "@/components/Map";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CalendarDays, Compass, Loader2, MapPin, ShieldCheck, Ticket } from "lucide-react";
import { Link, useParams } from "wouter";

export default function EventDetail() {
  const { id = "" } = useParams<{ id: string }>();
  const { data, isLoading, error } = trpc.catalog.event.useQuery({ slug: "adamantina", id: Number(id) }, { enabled: Boolean(id) && Number.isFinite(Number(id)) });
  if (isLoading) return <Shell><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#0d5c4d]" /></Shell>;
  if (error || !data) return <Shell><div className="rounded-2xl bg-white p-10 text-center text-sm text-[#71827c]">Evento não encontrado ou ainda não publicado.</div></Shell>;
  const { event, media } = data;
  const center = event.latitude && event.longitude ? { lat: Number(event.latitude), lng: Number(event.longitude) } : { lat: -21.685, lng: -51.073 };
  const starts = new Date(event.startsAt);
  return <Shell><Link href="/eventos" className="mb-6 inline-flex items-center text-sm font-bold text-[#0d5c4d]"><ArrowLeft className="mr-2 h-4 w-4" /> Voltar à agenda</Link><Card className="overflow-hidden rounded-[28px] border-[#d7e4d9] bg-white"><div className="grid gap-0 lg:grid-cols-[0.9fr_1.1fr]">{media[0] ? <img src={media[0].url} alt={media[0].altText ?? event.title} className="h-72 w-full object-cover lg:h-full" /> : <div className="flex min-h-72 items-center justify-center bg-gradient-to-br from-[#fff0d6] to-[#d9b56e] text-[#9a681d]"><CalendarDays className="h-16 w-16 opacity-45" /></div>}<div className="p-7 sm:p-10"><Badge className="border-0 bg-[#fff0d6] text-[10px] font-bold uppercase tracking-[0.16em] text-[#9a681d]">Agenda municipal</Badge><h1 className="mt-4 font-display text-4xl font-bold tracking-[-0.05em] text-[#123f36]">{event.title}</h1><p className="mt-4 text-base leading-7 text-[#71827c]">{event.description ?? "Confira esta atividade da agenda municipal."}</p><div className="mt-7 space-y-3 text-sm text-[#55716a]"><p className="flex gap-3"><CalendarDays className="h-5 w-5 shrink-0 text-[#c4703a]" /> {starts.toLocaleDateString("pt-BR", { dateStyle: "full" })} às {starts.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}{event.endsAt ? ` até ${new Date(event.endsAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}` : ""}</p>{event.venueName && <p className="flex gap-3"><MapPin className="h-5 w-5 shrink-0 text-[#c4703a]" /> {event.venueName}{event.address ? ` · ${event.address}` : ""}</p>}{event.organizer && <p className="flex gap-3"><Ticket className="h-5 w-5 shrink-0 text-[#c4703a]" /> Organização: {event.organizer}</p>}{event.price && <p className="flex gap-3"><Ticket className="h-5 w-5 shrink-0 text-[#c4703a]" /> {event.price}</p>}{event.accessibility && <p className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-[#0d5c4d]" /> {event.accessibility}</p>}</div></div></div></Card>{event.latitude && event.longitude && <Card className="mt-6 overflow-hidden rounded-[24px] border-[#d7e4d9] bg-white"><CardHeader><CardTitle className="font-display text-xl text-[#123f36]">Local do evento</CardTitle></CardHeader><CardContent className="p-0"><MapView className="h-[380px]" initialCenter={center} initialZoom={15} onMapReady={(map) => { new google.maps.marker.AdvancedMarkerElement({ map, position: center, title: event.venueName ?? event.title }); }} /></CardContent></Card>}</Shell>;
}
function Shell({ children }: { children: React.ReactNode }) { return <div className="min-h-screen bg-[#e8f1ea] px-5 py-10"><div className="mx-auto max-w-5xl"><Link href="/" className="mb-8 flex items-center gap-2 font-display font-bold text-[#123f36]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#0d5c4d] text-white"><Compass className="h-4 w-4" /></span> Viva Adamantina</Link>{children}</div></div>; }
