import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Compass, Loader2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "wouter";

export default function InviteAccept() { const { token = "" } = useParams<{ token: string }>(); const { user, isAuthenticated, loading } = useAuth(); const { data, isLoading, error } = trpc.invitations.get.useQuery({ token }, { enabled: Boolean(token) }); const accept = trpc.invitations.accept.useMutation(); const [done, setDone] = useState(false); if (loading || isLoading) return <Shell><Loader2 className="mx-auto h-7 w-7 animate-spin text-[#0d5c4d]" /></Shell>; if (error || !data) return <Shell><p className="text-center text-sm text-[#71827c]">Este convite é inválido ou expirou.</p></Shell>; if (!isAuthenticated) return <Shell><CardContent><div className="text-center"><ShieldCheck className="mx-auto h-10 w-10 text-[#0d5c4d]" /><h1 className="mt-5 font-display text-2xl font-bold text-[#123f36]">Convite para a Secretaria</h1><p className="mt-3 text-sm leading-6 text-[#71827c]">Entre com <strong>{data.email}</strong> para aceitar o perfil de {roleLabel(data.role)}.</p><Button onClick={() => startLogin()} className="mt-6 rounded-full bg-[#0d5c4d] font-bold text-white">Entrar para aceitar</Button></div></CardContent></Shell>; if (done) return <Shell><div className="text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-[#0d5c4d]" /><h1 className="mt-5 font-display text-3xl font-bold text-[#123f36]">Convite aceito</h1><p className="mt-3 text-sm text-[#71827c]">Sua conta já tem acesso à área municipal correspondente.</p><Link href="/admin" className="mt-6 inline-flex rounded-full bg-[#0d5c4d] px-5 py-3 text-sm font-bold text-white">Abrir painel</Link></div></Shell>; return <Shell><Card><CardHeader><CardTitle className="font-display text-2xl text-[#123f36]">Confirmar acesso municipal</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-[#71827c]">Você está autenticado como <strong>{user?.email}</strong>. Confirme para ativar seu perfil de {roleLabel(data.role)}.</p><Button onClick={async () => { await accept.mutateAsync({ token }); setDone(true); }} disabled={accept.isPending} className="mt-6 w-full rounded-full bg-[#0d5c4d] font-bold text-white">{accept.isPending ? <Loader2 className="mr-2 inline h-4 w-4 animate-spin" /> : null} Aceitar convite</Button></CardContent></Card></Shell>; }
function roleLabel(role: string) { return role === "municipal_admin" ? "administrador municipal" : role === "moderator" ? "moderador" : role === "analyst" ? "analista" : "parceiro"; }
function Shell({ children }: { children: React.ReactNode }) { return <div className="flex min-h-screen items-center justify-center bg-[#e8f1ea] px-5"><div className="w-full max-w-lg"><Link href="/" className="mb-8 flex items-center justify-center gap-2 font-display font-bold text-[#123f36]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#0d5c4d] text-white"><Compass className="h-4 w-4" /></span> Viva Adamantina</Link><Card className="rounded-[28px] border-[#d7e4d9] bg-white shadow-[0_20px_50px_rgba(39,73,57,0.12)]">{children}</Card></div></div>; }
