import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Check, Loader2, Plus } from "lucide-react";
import { useState } from "react";
export default function ContributionForm() { const { isAuthenticated } = useAuth(); const submit = trpc.submissions.create.useMutation(); const [entityType, setEntityType] = useState<"place" | "event">("place"); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [startsAt, setStartsAt] = useState(""); const [sent, setSent] = useState(false); const send = async () => { if (!isAuthenticated) return startLogin(); if (name.trim().length < 2) return; await submit.mutateAsync({ slug: "adamantina", entityType, payload: JSON.stringify(entityType === "place" ? { name: name.trim(), slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), type: "Sugestão da comunidade", description: description.trim() } : { title: name.trim(), slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), description: description.trim(), startsAt: startsAt ? new Date(startsAt).toISOString() : new Date().toISOString() }) }); setSent(true); setName(""); setDescription(""); setStartsAt(""); }; return <Card className="rounded-[24px] border-[#d7e4d9] bg-white"><CardHeader><CardTitle className="flex items-center gap-2 font-display text-xl text-[#123f36]"><Plus className="h-5 w-5 text-[#0d5c4d]" /> Sugira algo para a cidade</CardTitle><p className="text-sm text-[#71827c]">A Secretaria revisará sua sugestão antes de publicá-la.</p></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Button type="button" variant={entityType === "place" ? "default" : "outline"} onClick={() => setEntityType("place")} className="rounded-full">Novo local</Button><Button type="button" variant={entityType === "event" ? "default" : "outline"} onClick={() => setEntityType("event")} className="rounded-full">Novo evento</Button></div><Input value={name} onChange={(e) => setName(e.target.value)} placeholder={entityType === "place" ? "Nome do local" : "Nome do evento"} /><Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Descrição ou informações úteis" />{entityType === "event" && <Input type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} />}{sent && <p className="flex items-center gap-2 text-sm font-semibold text-[#0d5c4d]"><Check className="h-4 w-4" /> Sugestão enviada para moderação.</p>}<Button onClick={send} disabled={submit.isPending || name.trim().length < 2} className="rounded-full bg-[#0d5c4d] font-bold text-white">{submit.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />} Enviar sugestão</Button></CardContent></Card>; }
